# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

# Ensure we're running in the test environment
ENV['RAILS_ENV'] = 'test'

require 'cucumber/rails'

require 'selenium-webdriver'
require 'capybara'

# Sweep any Firefox/geckodriver processes left over from a prior test run or
# manual E2E session. Firefox 150 on macOS does not always exit when the
# WebDriver session is closed; a stale browser holds the Marionette port and
# causes the next geckodriver-spawned Firefox to exit silently with status 0,
# poisoning every @javascript scenario in the run.
AfterConfiguration do
  system("pkill -9 -f 'Firefox.app/Contents/MacOS/firefox' >/dev/null 2>&1")
  system('pkill -9 geckodriver >/dev/null 2>&1')
end

# Configure Selenium driver for JavaScript tests
Capybara.register_driver :selenium do |app|
  options = Selenium::WebDriver::Firefox::Options.new
  # On macOS, point to the standard Firefox.app location. On Linux (Docker),
  # Firefox is pre-installed via Mozilla's APT repository and in PATH; omitting
  # options.binary lets WebDriver find it automatically, which also prevents
  # Selenium Manager from downloading a freshly-released patch version that
  # may not yet be on Mozilla's FTP.
  options.binary = '/Applications/Firefox.app/Contents/MacOS/firefox' if RUBY_PLATFORM.include?('darwin')
  options.args << '--headless' # Run in headless mode
  options.args << '--no-sandbox'
  options.args << '--disable-dev-shm-usage'
  options.args << '--ignore-certificate-errors'
  options.args << '--allow-insecure-localhost'

  # Add this to disable security checks that interfere with WebDriver
  options.profile = Selenium::WebDriver::Firefox::Profile.new
  options.profile['network.stricttransportsecurity.preloadlist'] = false
  options.profile['security.cert_pinning.enforcement_level'] = 0

  Capybara::Selenium::Driver.new(app, browser: :firefox, options: options)
end

# Use rack_test for non-JavaScript tests (fast), Selenium for @javascript tests
Capybara.default_driver = :rack_test
Capybara.javascript_driver = :selenium
# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Use truncation for @javascript scenarios (Capybara server runs in a separate
# thread and cannot see data inside an uncommitted transaction) and transaction
# for everything else (fast rollback, no truncation overhead).
# The shared_connection monkeypatch is NOT needed with MySQL — each thread gets
# its own pooled connection.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise 'You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it.'
end

Before('@javascript') do
  DatabaseCleaner.strategy = :truncation
end

Before('not @javascript') do
  DatabaseCleaner.strategy = :transaction
end

Before do
  DatabaseCleaner.start
  ActionMailer::Base.deliveries.clear
  begin
    Resque.redis.redis.flushdb
  rescue StandardError
    # non-fatal: clear stale jobs when Redis is available
  end
end

After do
  DatabaseCleaner.clean
end
