production:
  paypal_login: 'register_api1.theaterwit.org'
  paypal_password: 'REDACTED_PAYPAL_PASSWORD'

development:
  paypal_login: 'test_1302729685_biz_api1.theaterwit.org'
  paypal_password: 'JAGWA69SRLYL3F7'
