delete_generated_reports:
  every: "1h"
  args:
  - report
  - 24
  description: 'Deletes generated reports older than 24 hours'
  queue: maintenance
  custom_job_class: AgeOutFileStore

delete_completed_imports:
  every: "1h"
  args:
  - import
  - 24
  description: 'Deletes imported raw data files after 24 hours'
  queue: maintenance
  custom_job_class: AgeOutFileStore

RunPendingOrderTasks:
  every: "5m"
  description: 'Run queued order tasks'
  queue: maintenance

GenerateCalendar:
  every: "4h"
  description: 'Write performance calendar to static cache'
  queue: sync
  args: 'performance_schedule.ics'

SendFlexPassReminders:
  every: '1d'
  description: 'Send flex pass fulfillment reminders'
  queue: notification

GenerateProductionSalesStatistics:
  cron: '30 0 * * *'
  description: 'Generate statistics for previous days sales'
  queue: maintenance

CheckPerformanceAllocationTriggers:
  cron: '0 1 * * *'
  description: 'Run any existing allocation triggers'
  queue: maintenance

UpdateAttendeesFromSalesforce:
  cron: '0 10 * * *'
  description: 'Update today''s attendee records from Salesforce'
  queue: sync

PurgeExpiredSpecialOffers:
  cron: '0 1 * * 0'
  description: 'Purge expired special offers'
  queue: maintenance

MarkInactiveShows:
  every: "1d"
  description: 'Productions/Theaters that have been inactive for over 6 months and not updated since then are marked as ''Inactive''.'
  queue: maintenance

LinkHistoricPerformanceHoldsToAddressOfRecord:
  every: "1d"
  description: "Once a performance is in the past, link the hold to the address card of record"
  queue: maintenance

DeleteAbandonedOrders:
  every: "8m"
  description: "An order can only existing in PROCESSING state for 8 minutes"
  queue: maintenance
