# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d0c2bfc302021738821cc6861b804130d680876dbdfe6f44f695000a87997f658641a7b8d6b98b5f7898b0776482209d180e823b668ff27090c8e57de523ad

test:
  secret_key_base: 60814a9671423ab7e769ed8971e35ebd497d7b75de320b8507d345d3ac414a378b25d8640286b3140cd4a28c779cfb8e5e6126559b7b6041649dbecae6ca68a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
