module RecurringOrder

  extend ActiveSupport::Concern
  included do
    has_many :recurring_payments, :foreign_key=>:order_id
    accepts_nested_attributes_for :recurring_payments
  end

  def reactivate
    self.recurring_profile.reactivate
  end

  def suspend!
    raise "Recurringorder.suspend not yet implemented!"
  end

  def cancel
    self.recurring_profile.cancel
  end

  def recurring_profile
    raise "recurring_profile not yet implmeneted"
  end

  def recurring_offer
    raise "recurring_offer not yet implemented"
  end

  def create_recurring_payment(note = nil, additional_info = {})
    payment = RecurringPayment.new
    payment.amount = additional_info[:amount] unless additional_info[:amount].blank?
    payment.note = note || "Automatically created"
    payment.transaction_id = additional_info[:invoice_id]
    payment.ipn_track_id = additional_info[:id]
    payment.processed_on = additional_info[:processed_on]
    payment.payment_fee = additional_info[:payment_fee]
    payment.payment_type = CreditCardPaymentType.first
    self.payments << payment
    payment
  end

  def create_recurring_payment!(note = nil, additional_info = {})
    self.create_recurring_payment(note, additional_info)
    self.save!
  end
  
  def create_missing_recurring_payment(payment_date, amount)
    payment = RecurringPayment.new
    payment.amount = amount
    payment.note = "Automatically generated by repair"
    payment.processed_on = payment_date
    payment.payment_type = CreditCardPaymentType.first
    self.recurring_payments <<  payment
    payment
  end

  def notify_suspended
    unless $EMAIL_ADDRESS.nil?
      task = NotificationTask.new(:execute_at => Time.now, :notifications => [$EMAIL_ADDRESS['box_office'], $EMAIL_ADDRESS['supervisor_notifications']].join(','),
        :method_symbol => :suspension_alert) 
      self.tasks << task
    end
  end

end
