module RecurringOrder
  extend ActiveSupport::Concern

  included do
    has_many :recurring_payments, foreign_key: :order_id
    accepts_nested_attributes_for :recurring_payments
  end

  delegate :reactivate, to: :recurring_profile

  def suspend!
    raise 'Recurringorder.suspend not yet implemented!'
  end

  delegate :cancel, to: :recurring_profile

  def recurring_profile
    raise 'recurring_profile not yet implmeneted'
  end

  def recurring_offer
    raise 'recurring_offer not yet implemented'
  end

  def create_recurring_payment(note = nil, additional_info = {})
    payment = RecurringPayment.new
    payment.amount = additional_info[:amount] if additional_info[:amount].present?
    payment.note = note || 'Automatically created'
    payment.transaction_id = additional_info[:invoice_id]
    payment.ipn_track_id = additional_info[:id]
    payment.processed_on = additional_info[:processed_on]
    payment.payment_type = CreditCardPaymentType.first
    payments << payment
    payment
  end

  def create_recurring_payment!(note = nil, additional_info = {})
    create_recurring_payment(note, additional_info)
    save!
  end

  def create_missing_recurring_payment(payment_date, amount)
    payment = RecurringPayment.new
    payment.amount = amount
    payment.note = 'Automatically generated by repair'
    payment.processed_on = payment_date
    payment.payment_type = CreditCardPaymentType.first
    recurring_payments << payment
    payment
  end

  def notify_suspended
    return if Rails.configuration.x.email_address['box_office'].nil?

    task = NotificationTask.new(execute_at: Time.now, notifications: [Rails.configuration.x.email_address['box_office'], Rails.configuration.x.email_address['supervisor_notifications']].join(','),
                                method_symbol: :suspension_alert, order: self)
    task.save
  end
end
